---
title: "buchman-distance"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{buchman-distance}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
#library(simulationBands)
```

```{r}
library(tidyverse)
f_1 <- data.frame(t = 1:100,
                  y = (exp((1+1:100/25)))) %>%
  mutate(x = exp(1+c(1:50/25, 1 + 51:100/50)))

f_1 <- f_1 %>% filter(t %% 10 == 0) 

f_1 %>%
  ggplot(aes(x = x, y = y)) +
  geom_path() +
  geom_point()
```

```{r}
# simulate a set of functions
sim_f <- data.frame()
B = 1000
f_1_length <- nrow(f_1)
for (s_idx in 1:B) {
  x_shift <- rnorm(n=1,sd = 3)
  y_shift <- rnorm(n =1, sd = 5)
  sim_f_inner <- f_1 %>% 
    mutate(x = x + rnorm(n = f_1_length, sd = 2) + x_shift,
           y = y + rnorm(n = f_1_length, sd = 2) + y_shift,
           sim = s_idx) 
  sim_f <- rbind(sim_f, sim_f_inner)
}
```

```{r fig.align="center"}
f_1 %>%
  ggplot(aes(x = x, y = y)) +
  geom_path() +
  geom_point() +
  geom_line(data = sim_f, aes(group = factor(sim)), alpha = .01) +
  theme_minimal() +
  theme(aspect.ratio = 1)
```

```{r message = F, warning =F}
devtools::load_all("~/Documents/CMU/research/EpiCompare/")
```

```{r}
dist_f <- function(df1,df2) {
  sqrt(sum(EpiCompare::dist_between_paths(df1,df2)))
  }

dist_df <- sim_f %>%
  group_by(sim) %>%
  nest() %>%
  mutate(dist = purrr::map(data, function(df) dist_f(df %>% select(x,y),
                                                    f_1 %>% select(x,y)))) %>%
  select(-data) %>%
  unnest(cols = c(dist)) %>%
  ungroup() %>%
  mutate(rank = - rank(dist))

sim_f2 <- sim_f %>% left_join(dist_df, by = "sim")

```

```{r fig.align="center"}
f_1 %>%
  ggplot(aes(x = x, y = y)) +

  geom_line(data = sim_f2, aes(group = factor(rank), color = dist)) +
  theme_minimal() +
  theme(aspect.ratio = 1) +
  geom_path() +
  geom_point() +
  scale_color_gradient2()
```

```{r}
vis_list <- list()
splits <- dist_df %>%
  pull(dist) %>%
  quantile( prob = seq(0,1, length.out = 13))

min_max <- dist_df %>%
  pull(dist) %>% range()

for (v_idx in 1:12){
  lower_split <- splits[v_idx]
  upper_split <- splits[v_idx+1]
  vis_list[[v_idx]] <- f_1 %>%
    ggplot(aes(x = x, y = y)) +
    geom_line(data = sim_f2 %>% filter(dist <= upper_split, 
                                       dist >= lower_split),
              aes(group = factor(sim)), alpha = .1) +
    theme_minimal() +
    theme(aspect.ratio = 1, legend.position = "none") +
    scale_color_gradient2(lim = min_max) +
    geom_path(color = "cyan") +
    geom_point(color = "cyan") 
}
```


```{r fig.height = 15, fig.width = 6, fig.align="center"}
library(gridExtra)
grid.arrange(grobs = vis_list, nrow = 6)
```


