# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' calculates distances between points of 2 matrices
#'
#' \code{C++} function taken from
#' https://www.r-bloggers.com/2019/09/matrix-cross-distances-using-rcpp/
#'
#' @param m1 first matrix (n x p)
#' @param m2 second matrix (m x p)
#'
crossdist <- function(m1, m2) {
    .Call('_simulationBands_crossdist', PACKAGE = 'simulationBands', m1, m2)
}

